apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "1.28.0"
controlPlaneEndpoint: "k8s-api.example.com:6443"
networking:
  podSubnet: "10.244.0.0/16"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.10.1.10"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-labels: "node-role.kubernetes.io/control-plane="
    authorization-mode: "Webhook"
